### ISSUE TITLE
FlipBackSlash() is incompatible with UNC file paths

### ISSUE THREAD

**Issue by Chris-M-P** [AndriSignorell/DescToolsAddIns#4]
Applying FlipBackSlash() to a UNC file path (or anything else with a double back slash) results in a single forward slash, e.g.
"\\servername\path" becomes "/servername/path"

**Comment by AndriSignorell** [comment]
Thanks for your message. This behaviour was by design. I thought this to be generally useful. 
However I realize that it might not be and changed the logic in v1.7 so, that the user can control with an option ReplaceDoubleSlash (TRUE or FALSE) whether double backslashes should be replaced by single slashes. The default is FALSE, which would react as you expected.
Users wanting the old behaviour back set options(ReplaceDoubleSlash=TRUE).

**Comment by AndriSignorell** [comment]
Done.
